---
parser: "babel-eslint"
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"

  # There are a few places where we do if(Meteor.isServer) { import ... }.
  # Ideally we'd refactor so this was unneccesary, but for now the import
  # *has* to be conditional, so tell eslint to allow this:
  allowImportExportEverywhere: true
reportUnusedDisableDirectives: true
extends: "eslint:recommended"
rules:
  # These are implied by eslint:recommended, but we haven't gotten around to
  # fixing them yet:
  no-undef: ["off"]
  no-unused-vars: ["off"]
  no-empty: ["off"]
  no-inner-declarations: ["off"]
  no-prototype-builtins: ["off"]
